version: '3'
services:
  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # working_dir: /genar/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
