# Generated by Django 2.0.6 on 2018-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='image',
            field=models.CharField(default='./images/nonpicture.png', max_length=100),
        ),
    ]
