# Generated by Django 2.0.6 on 2018-06-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0002_integrante_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrante',
            old_name='image',
            new_name='imagen',
        ),
    ]
