# Generated by Django 2.0.6 on 2018-06-27 02:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0009_auto_20180625_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='archivo',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/'),
        ),
    ]
