# Generated by Django 2.0.8 on 2018-09-10 04:01

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0011_auto_20180627_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='images/'),
        ),
    ]
